### PR TITLE
Disable REPL if env is no TTY

### PR DESCRIPTION
**Pull request by jaumard**
Fix https://github.com/trailsjs/trails/issues/222 https://github.com/trailsjs/trails/issues/218

### CODE REVIEW

**Comment by jaumard** [comment]
With this no more problem on Heroku, Docker, pipe command or whatever env that doesn't allow repl. 
cc @scott-wyatt @tjwebb @weyj4

**Comment by gliwka** [comment]
Maybe add a log message on the debug level, indicating, that the repl has been deactivated, because there is no real TTY?

**Comment by scott-wyatt** [comment]
This looks fantastic to me!

**Comment by konstantinzolotarev** [comment]
@tjwebb Any comments on this ?

**Comment by jaumard** [comment]
@tjwebb up :)

**Comment by gliwka** [comment]
@tjwebb @jaumard What's up with this PR? Still open?

**Comment by jaumard** [comment]
we're waiting for @tjwebb but it look quite busy those days. @konstantinzolotarev can we merge/deploy this ?

**Review by scott-wyatt — APPROVED** [review]
This looks good.

**Comment by tjwebb** [comment]
Sorry guys, I missed this one. Thanks @gliwka for bringing this up in Gitter (https://gitter.im/trailsjs/trails?at=57df7115df21a757300ae10b).

This lgtm, merging now and I'll publish a release this evening.

**Pull request merged**
